# Offense count: 22
# Configuration parameters: AllowKeywordBlockArguments.
Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'spec/helper/get_defaults.rb'
    - 'spec/helper/get_values_init.rb'
    - 'spec/shared_examples/compose.rb'
    - 'spec/shared_examples/config.rb'
    - 'spec/shared_examples/exec.rb'
    - 'spec/shared_examples/image.rb'
    - 'spec/shared_examples/install.rb'
    - 'spec/shared_examples/machine.rb'
    - 'spec/shared_examples/params.rb'
    - 'spec/shared_examples/plugin.rb'
    - 'spec/shared_examples/registry.rb'

# Offense count: 7
Lint/UselessAssignment:
  Exclude:
    - 'spec/classes/networks_spec.rb'
    - 'spec/defines/run_spec.rb'
    - 'spec/helper/get_defaults.rb'
    - 'spec/shared_examples/compose.rb'
    - 'spec/shared_examples/image.rb'
    - 'spec/shared_examples/machine.rb'

# Offense count: 20
# Configuration parameters: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 291

# Offense count: 11
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns, inherit_mode.
# AllowedMethods: refine
Metrics/BlockLength:
  Max: 125

# Offense count: 7
# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 7

# Offense count: 17
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 67

# Offense count: 24
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 462

# Offense count: 2
# Configuration parameters: CountKeywordArgs, MaxOptionalParameters.
Metrics/ParameterLists:
  Max: 9

# Offense count: 14
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 71

# Offense count: 47
# Configuration parameters: ForbiddenDelimiters.
# ForbiddenDelimiters: (?i-mx:(^|\s)(EO[A-Z]{1}|END)(\s|$))
Naming/HeredocDelimiterNaming:
  Exclude:
    - 'spec/acceptance/docker_custom_source_spec.rb'
    - 'spec/acceptance/docker_full_spec.rb'
    - 'spec/acceptance/machine_spec.rb'
    - 'spec/spec_helper_acceptance_local.rb'

# Offense count: 8
# Configuration parameters: MinSize.
Performance/CollectionLiteralInLoop:
  Exclude:
    - 'spec/defines/exec_spec.rb'
    - 'spec/defines/image_spec.rb'
    - 'spec/defines/registry_spec.rb'
    - 'spec/defines/run_spec.rb'
    - 'spec/defines/secrets_spec.rb'
    - 'spec/defines/services_spec.rb'
    - 'spec/defines/stack_spec.rb'
    - 'spec/defines/swarm_spec.rb'

# Offense count: 41
# Configuration parameters: Prefixes, AllowedPatterns.
# Prefixes: when, with, without
RSpec/ContextWording:
  Enabled: false

# Offense count: 32
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Enabled: false

# Offense count: 102
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 52

# Offense count: 2
RSpec/ExpectInHook:
  Exclude:
    - 'spec/acceptance/docker_full_spec.rb'

# Offense count: 6
# Configuration parameters: Max.
RSpec/IndexedLet:
  Exclude:
    - 'spec/acceptance/docker_params_changed_spec.rb'

# Offense count: 38
RSpec/MultipleExpectations:
  Max: 4

# Offense count: 24
# Configuration parameters: EnforcedStyle, IgnoreSharedExamples.
# SupportedStyles: always, named_only
RSpec/NamedSubject:
  Exclude:
    - 'spec/classes/compose_spec.rb'
    - 'spec/classes/images_spec.rb'
    - 'spec/classes/init_spec.rb'
    - 'spec/classes/machine_spec.rb'
    - 'spec/classes/networks_spec.rb'
    - 'spec/classes/plugins_spec.rb'
    - 'spec/defines/image_spec.rb'
    - 'spec/defines/plugin_spec.rb'
    - 'spec/defines/run_spec.rb'
    - 'spec/defines/services_spec.rb'

# Offense count: 5
# Configuration parameters: AllowedGroups.
RSpec/NestedGroups:
  Max: 4

# Offense count: 59
# Configuration parameters: AllowedPatterns.
# AllowedPatterns: ^expect_, ^assert_
RSpec/NoExpectationExample:
  Exclude:
    - 'spec/acceptance/compose_v3_spec.rb'
    - 'spec/acceptance/docker_custom_source_spec.rb'
    - 'spec/acceptance/docker_full_spec.rb'
    - 'spec/acceptance/docker_spec.rb'
    - 'spec/acceptance/machine_spec.rb'
    - 'spec/acceptance/network_spec.rb'
    - 'spec/acceptance/plugin_spec.rb'
    - 'spec/acceptance/stack_spec.rb'
    - 'spec/acceptance/volume_spec.rb'
    - 'spec/acceptance_swarm/swarm_spec.rb'

# Offense count: 3
RSpec/StubbedMock:
  Exclude:
    - 'spec/unit/lib/facter/docker_spec.rb'
