---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  include_todos: true
appveyor.yml:
  delete: true

Gemfile:
  optional:
    ":development":
    - gem: ruby-pwsh
    - gem: github_changelog_generator
    ":system_tests":
    - gem: rspec-retry
Rakefile:
  changelog_since_tag: 3.5.0
spec/spec_helper.rb:
  unmanaged: true
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/pr_test.yml:
  unmanaged: true
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.travis.yml:
  delete: true
