diff /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/init.pp .
diff /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/compose.pp .
diff /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/exec.pp .
diff /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/image.pp .
diff /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/run.pp .
diff /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/secrets.pp .
diff /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/services.pp .
diff /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/stack.pp .
diff /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/swarm.pp .
cp /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/init.pp .
cp /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/compose.pp .
cp /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/exec.pp .
cp /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/image.pp .
cp /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/run.pp . .
cp /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/run.pp .
cp /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/secrets.pp .
cp /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/services.pp .
cp /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/stack.pp .
cp /Users/sheena/repos/dockerfix/puppetlabs-docker/manifests/swarm.pp .
